name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/387754905624/locations/global/workloadIdentityPools/github-oidc/providers/github
          service_account: kc-deployer@solar-safeguard-472521-a1.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: solar-safeguard-472521-a1

      - name: Deploy KindCompanion API
        run: |
          gcloud run deploy kindcompanion-api \
            --source ./backend \
