name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Set project
        run: gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Deploy hello service
        run: |
          gcloud run deploy kindcompanion-hello \
            --image gcr.io/cloudrun/hello \
            --region ${{ vars.GCP_REGION || 'europe-west2' }} \
            --allow-unauthenticated \
            --quiet
