name: Auth Smoke Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Auth to Google Cloud (OIDC, hard-coded)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/387754905624/locations/global/workloadIdentityPools/github-oidc/providers/github
          service_account: kc-deployer@solar-safeguard-472521-a1.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Prove auth works
        run: |
          gcloud auth list --filter=status:ACTIVE --format="value(account)"
          gcloud config set project solar-safeguard-472521-a1
          gcloud projects describe solar-safeguard-472521-a1 --format="value(projectNumber)"
